### ISSUE TITLE
Parse and resolve fails on `address.code`

### ISSUE THREAD

**Issue by bkushigian** [hyperledger/solang#1537] opened 2023-09-16 03:49 UTC
I know this is an EVM bytecode thing which y'all don't support, not sure if there's a good way to handle this? But yeah, would be great to be able to handle this after resolution! The below example uses `AddressCode.sol` with contents:
```solidity
// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity >=0.8.0;

contract AddressCode {
    function addressCode(address addr) public view returns (uint256) {
        return addr.code.length;
    }
}
```
and the `solang_parser` binary generated from [this testing repo](https://github.com/bkushigian/SolangParse4Debugging) (it just runs parse_and_resolve).

```
$ solang_parser testcase/address_code/AddressCode.sol 

=====  Error: testcase/address_code/AddressCode.sol  =====
error: 'code' not found
  ┌─ /Users/benku/solang_parse/testcase/address_code/AddressCode.sol:6:16
  │
6 │         return addr.code.length;
  │                ^^^^^^^^^

$ solc testcase/address_code/AddressCode.sol
Compiler run successful. No output generated.
```

**Comment by xermicus** [comment] 2023-09-16 09:47
Closing this is a duplicate of #809 But many thanks @bkushigian  for reporting this (and all your other bugs!) to us 👍

**Closed by xermicus** 2023-09-16 09:47 UTC
Labels: enhancement
