### ISSUE TITLE
Inconsistent behaviour when calling function via contract type name

### ISSUE THREAD

**Issue by xermicus** [hyperledger/solang#1007] opened 2022-09-08 10:42 UTC
Given the following base contract:

```solidity
contract Base {
    uint256 public something = 0;

    function nop() public pure {}

    function set(uint256 val) public {
        something = val;
    }
}
```
And the following case `A`:
```solidity
contract A {
    function a() public pure {
        Base.nop();
    }
}
```
Solang compiles this just fine. Furthermore, consider the following case `B`:
```solidity
contract B {
    function b() public {
        Base.set(1);
    }
}
```
Solang crashes during compilation (target either `substrate` or `solana`):
```
thread 'main' panicked at 'get_storage_slot called on non-storage variable', src/codegen/cfg.rs:1879:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Where as `solc` behaves more in a way I'd expect. For both cases it gets the same error:
```
❯ solc --bin foo.sol
Error: Cannot call function via contract type name.
  --> foo.sol:27:9:
   |
17 |         Base.nop();
   |         ^^^^^^^^^^

Error: Cannot call function via contract type name.
  --> foo.sol:33:9:
   |
23 |         Base.set(1);
   |         ^^^^^^^^^^^
```
Is there a reason we allow case `A`? If so, we should at least restrict it to `pure` functions. But this looks more like a bug to me.

**Comment by seanyoung** [comment] 2022-09-08 12:19
This is definitely broken. I think the issue is that you can call a base contract via the base name, which means you can call a function of a base contract which has been overridden. For example:
```solidity
contract Base {
    uint256 public something = 0;

    function nop() public pure {}

    function set(uint256 val) virtual public {
        something = val;
    }
}

contract B {
    function b() public {
       // Calls function in base contract Base,  sets something to 1
        Base.set(1);
    }
    function set(uint256 val) virtual override public {
        something = val + 1024;
    }
}
```

**Comment by xermicus** [comment] 2022-09-08 13:03
Right, I see. Should I look into fixing this now? I discovered this bug because I want to add a Syntax for specifying constructors. I was going to use the Syntax you suggested in discord earlier:

```solidity
contract C {
    constructor a() {}
    constructor b() {}
}
 
function f() {
    C c = new C.a();
}
```
But I think if we want to do it this way, it would be good to have this bug fixed first?

**Comment by seanyoung** [comment] 2022-09-08 13:58
> But I think if we want to do it this way, it would be good to have this bug fixed first?

It might be helpful to get this working - it will probably also help with your understanding of this code.

FIrst of all, for method calls there are two code path, one with name arguments `foo,bar({a: true, b: 102})` and the usual positional arguments `foo.bar(true, 102)`. Both will need fixing and tests added. The example you gave is an excellent test, it should say is not a base contract or seomthing like that.

This is the code that checks if the method call is on a contract type: https://github.com/hyperledger/solang/blob/main/src/sema/expression.rs#L5825-L5858 (for positional calls). Interestingly there is no else branch with an error message. I'm not quite sure why that is.

A few lines down from there on https://github.com/hyperledger/solang/blob/main/src/sema/expression.rs#L5932,
`resolve_free_function_with_namespace()` is called. This should resolve "free functions", functions outside of contracts. These functions can be imported from another file via an import object:

// a.sol
function hello() { print("Hello"; }
// b.sol
import "a.sol" as meh;
contract c {
   function x() {
       meh.hello();
   }
}
```
What is happening here is that `fn resolve_free_function_with_namespace()` is resolving `Base.set`. But it should not resolve functions in contracts, those are not free functions. There is a bug in there somewhere.

**Comment by xermicus** [comment] 2022-09-08 14:37
Much thanks for all the pointers! Going to have a shot at this :ok_hand:

**Closed** 2022-09-14 12:41 UTC
Labels: bug
