### ISSUE TITLE
Language server panics

### ISSUE THREAD

**Issue by LucasSte** [hyperledger/solang#984] opened 2022-08-23 12:21 UTC
This file crashes the language server:
```solidity
import 'solana';

library SystemInstruction {
    address constant systemAddress = address"Sysvar1nstructions1111111111111111111111111";
    enum TokenInstruction {
        CreateAccount,
        Assign,
        Transfer,
        CreateAccoundWithSeed,
        AdvanceNounceAccount,
        WithdrawNonceAccount,
        InitializeNonceAccount,
        AuthorizeNonceAccount,
        Allocate,
        AllocateWithSeed,
        AssignWithSeed,
        TransferWithSeed,
        UpgradeNonceAccount
    }

    function create_account(address from, address to, uint64 lamports, uint64 space, address owner) internal {
        AccountMeta[2] metas = [
            AccountMeta({pubkey: from, is_signer: true, is_writable: true}),
            AccountMeta({pubkey: to, is_signer: true, is_writable: true})
        ];
    }    
}
```

The error is: 
```
thread 'main' panicked at 'index out of bounds: the len is 23 but the index is 24', src/sema/file.rs:78:13
```

**Comment by seanyoung** [comment] 2022-09-02 13:11
I can't reproduce this on the `main` branch

**Comment by LucasSte** [comment] 2022-09-02 13:29
> I can't reproduce this on the `main` branch

I have used the 0.1.12 release available on VSCode's marketplace.

**Comment by seanyoung** [comment] 2022-09-02 14:03
Then we can close the issue

**Closed by seanyoung** 2022-09-02 14:03 UTC
Labels: bug
